jms_cleaning/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib import admin

from jms_cleaning.settings import MEDIA_ROOT, STATIC_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Static
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    # Media Root
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # Site URLs
    url(r'', include('jms_site.urls'))
]

jms_site/urls.py
from django.conf.urls import url
from .views import get_index, get_robots, get_about, get_sitemap, get_contact, get_service, get_services, get_testimonials, get_gallery
urlpatterns = [


    # Home Page
    url(r'^$', get_index, name='home'),


    # About Page
    url(r'^about/$', get_about, name='about'),

    # Services Page
    url(r'^services/$', get_services, name='services'),

    # Service Page
    url(r'^services/(?P<service_slug>[\w-]+)/$', get_service, name='service'),
    url(r'^services/(?P<service_slug>[\w-]+)/essex/', get_service),
    url(r'^services/(?P<service_slug>[\w-]+)/basildon/$', get_service),
    url(r'^services/(?P<service_slug>[\w-]+)/rayleigh/$', get_service),
    url(r'^services/(?P<service_slug>[\w-]+)/benfleet/$', get_service),
    url(r'^services/(?P<service_slug>[\w-]+)/hockley/$', get_service),
    url(r'^services/(?P<service_slug>[\w-]+)/southend/$', get_service),

    url(r'^office-cleaning-essex/$', get_index),
    url(r'^office-cleaning-southend/$', get_index),
    url(r'^commercial-cleaning-essex/$', get_index),
    url(r'^commercial-cleaning-southend/$', get_index),
    url(r'^end-of-tenancy-cleaning-essex/$', get_index),
    url(r'^end-of-tenancy-cleaning-southend/$', get_index),

    # Testimonials Page
    url(r'^testimonials/$', get_testimonials, name='testimonials'),

    # Gallery Page
    url(r'^gallery/$', get_gallery, name='gallery'),

    # Contact Page
    url(r'^contact/$', get_contact, name='contact'),

    url(r'^sitemap.xml/$', get_sitemap),
    url(r'^robots.txt/$', get_robots)
]

jms_site/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now

from django.db import models

from tinymce.models import HTMLField

# Create your models here.

# About

class About(models.Model):
    about = HTMLField()

    def __unicode__(self):
        return 'About - ' + str(self.id)

    class Meta:
        verbose_name = 'About'
        verbose_name_plural = 'About Information'




# Services
class Service(models.Model):
    service = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, default='', editable=False)
    meta = models.TextField()
    brief = HTMLField()
    description = HTMLField()
    image = models.ImageField(upload_to='services')
    popular = models.BooleanField()
    rank = models.IntegerField()

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }

    def save(self, *args, **kwargs):
        value = self.service
        self.slug = slugify(value, allow_unicode=True)
        super(Service, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.service

    class Meta():
        verbose_name = "Service"
        verbose_name_plural = 'Services'

# Service Blurb
class ServiceBlurb(models.Model):
    text = HTMLField()

    def __unicode__(self):
        return 'Service - ' + str(self.id)

    class Meta():
        verbose_name = 'Service Blurb'
        verbose_name_plural = 'Service Blurbs'


# Testimonialsa
class Testimonials(models.Model):
    name = models.CharField(max_length=200, default='Anonymous')
    company = models.CharField(max_length=400, blank=True, null=True)
    testimonial = models.TextField()
    date = models.DateField(
        editable=False,
        default=now()
    )

    def __unicode__(self):
        return self.name

    class Meta():
        verbose_name = 'Testimonial'
        verbose_name_plural = 'Testimonails'



# Job Upload
class JobPost(models.Model):
    title = models.CharField(max_length=200)
    service = models.ForeignKey(Service)
    testimonial = models.ForeignKey(Testimonials, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    before_img_1 = models.ImageField(upload_to='job_post/before', blank=True, null=True)
    before_img_2 = models.ImageField(upload_to='job_post/before', blank=True, null=True)
    before_img_3 = models.ImageField(upload_to='job_post/before', blank=True, null=True)
    after_img_1 = models.ImageField (upload_to='job_post/after', blank=True, null=True)
    after_img_2 = models.ImageField (upload_to='job_post/after', blank=True, null=True)
    after_img_3 = models.ImageField (upload_to='job_post/after', blank=True, null=True)

    def __unicode__(self):
        return self.title

    class Meta():
        verbose_name = 'Job Post'
        verbose_name_plural = 'Job Posts'



# Contact Request
class ContactRequest(models.Model):
    name = models.CharField(max_length=200)
    number = models.CharField(max_length=12)
    email = models.EmailField(max_length=200)
    service = models.ForeignKey(Service, related_name='service_request')
    message = models.TextField()

    def __unicode__(self):
        return str(self.service) + ' Request' + ' - ' + self.name

    class Meta():
        verbose_name = "Contact Request"
        verbose_name_plural = 'Enquiries'

templates/contact/contact_form.html
<p class="title">Get in Touch</p>
<div id='contact-form' class="padding-bottom">
    <form class='form' method="POST">
        {% csrf_token %}
        {{ contact_form }}

        <div class="contact-row">

            <div class="gdpr">
                <input type="checkbox"  id="tick" onchange="document.getElementById('contact-btn').disabled = !this.checked;" />
                <p>By using this form you agree with the storage and handling of your data by this website.</p>
            </div>
            <div id='contact-submit'>
                <button type="submit" class="btn" name="contact-btn" id="contact-btn" disabled>Contact Me!</button>
            </div>
        </div>
    </form>
</div>

{% block bottom_js %}
    <script type="text/javascript">
        $('#id_name').addClass('group-1');
        $('label[for=id_name]').addClass('group-1');

        $('.group-1').wrapAll('<div class=col-md-3>');

        $('#id_number').addClass('group-2');
        $('label[for=id_number]').addClass('group-2');

        $('.group-2').wrapAll('<div class=col-md-3>');

        $('#id_email').addClass('group-3');
        $('label[for=id_email]').addClass('group-3');

        $('.group-3').wrapAll('<div class=col-md-3>');

        $('#id_service').addClass('group-4');
        $('label[for=id_service]').addClass('group-4');

        $('.group-4').wrapAll('<div class=col-md-3>');

        $('.col-md-3').wrapAll('<div class=contact-row>')

    </script>

{% endblock %}

templates/contact/contact_page.html
{% extends 'base/index.html' %}

{% block head_js %}
    <title>JMS - Contact</title>

    <meta name="description" content="Get in touch today for a free non-obligatory quote! We can give either a rough
     estimate over the phone, or we will send someone down to give you a tailored quotation to fit exactly what you need!" />

    <meta property="og:description" content="Get in touch today for a free non-obligatory quote! We can give either a rough
     estimate over the phone, or we will send someone down to give you a tailored quotation to fit exactly what you need!"/>

{% endblock %}

{% block content %}


     <h1 class="title">Contact Us</h1>
        <article id="contact-page" class="container padding-bottom text">
            <p>If you are unsure, or would like to call up to find out more, please find either our contact information,
                or the contact form below and we will get back to you as quickly as possible
            </p>
            {% include 'contact/map.html' %}
        </article>

        <div id="contact" class="img-break" title="background-3">
            <div class="container">

                {% include 'contact/contact_form.html' %}
            </div>
        </div>
{% endblock %}

templates/contact/map.html
            <div id="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63904.07041051893!2d0.63026460931656!3d51.568350793829595!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8da32aa5a105b%3A0x3a1eae33c8d2ffc7!2sBlenheim+Chase%2C+Southend-on-Sea%2C+Leigh-on-Sea+SS9+3BZ!5e0!3m2!1sen!2suk!4v1560898377016!5m2!1sen!2suk" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                <div class="map-text text">
                    <div id="areas">
                        <p class="sub-title">Areas We Serve</p>
                        <ul>
                            <li>- Southend</li>
                            <li>- Westcliff</li>
                            <li>- Leigh On Sea</li>
                            <li>- Hockley</li>
                            <li>- Rayleigh</li>
                            <li>- Basildon</li>
                            <li>- Benfleet</li>
                        </ul>
                    </div>
                    <div id="contact-details">
                        <p class="sub-title">Contact Details</p>
                        <p>01702 667455</p>
                        <p>info.jmscleaningservices@gmail.com</p>
                    </div>
                </div>
            </div>